version: '3.8'

services:
  inboxed:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      # Mount source code for hot reloading
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./tsconfig.json:/app/tsconfig.json
      # Mount node_modules as a volume to avoid conflicts
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
      - ALLOWED_ORIGINS=*
    command: npm run dev

volumes:
  node_modules:
